apiVersion: skaffold/v2alpha3
kind: config
deploy: 
  kubectl:
    manifests:
      - ./infra/k8s/*
build: 
  local:
    push: false
  artifacts:
    - image: sergiocrol/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: sergiocrol/client-ticketing
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
    - image: sergiocrol/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .